#ifndef LINE_RECOVERY_CONFIG_H
#define LINE_RECOVERY_CONFIG_H

#define LINE_REACQUIRE_COUNT (3U)
#define LINE_ALIGN_DURATION_MS (300U)
#define LINE_RECOVERY_ESTIMATE_STALE_MS (20U)
#define LINE_RECOVERY_MIN_CONFIDENCE (40U)
#define LINE_SEEK_COMMAND (100)
#define LINE_SEEK_LIMITED_COMMAND (80)
#define LINE_SEEK_HIGH_YAW_DPS (120.0f)
#define LINE_ALIGN_COMMAND_LIMIT (80)

#endif
