#ifndef LINE_CASCADE_CONFIG_H
#define LINE_CASCADE_CONFIG_H

#define LINE_CASCADE_ESTIMATE_STALE_MS (20U)
#define LINE_CASCADE_MAX_COMMAND (140)
#define LINE_CASCADE_POSITION_KP (14.0f)
#define LINE_CASCADE_POSITION_KD (0.010f)
#define LINE_CASCADE_YAW_RATE_PER_COMMAND (0.8f)
#define LINE_CASCADE_ANGLE_KP (1.5f)
#define LINE_CASCADE_ANGLE_KD (0.55f)
#define LINE_CASCADE_DERIVATIVE_ALPHA (0.10f)
#define LINE_CASCADE_MAX_POSITION_COMMAND (90.0f)
#define LINE_CASCADE_MAX_DT_MS (50U)
#define LINE_CASCADE_MAX_YAW_ERROR_DEG (20.0f)
#define LINE_CASCADE_ACCEL_STEP (4)
#define LINE_CASCADE_DECEL_STEP (60)
#define LINE_CASCADE_TURN_SLEW_STEP (10)

#endif
