#ifndef LINE_FEATURE_CONFIG_H
#define LINE_FEATURE_CONFIG_H

#define LINE_FEATURE_STALE_MS (20U)
#define LINE_FEATURE_JUMP_ERROR (3.0f)
#define LINE_FEATURE_GROUP_PENALTY (20)
#define LINE_FEATURE_WIDE_PENALTY (10)
#define LINE_FEATURE_JUMP_PENALTY (15)

#endif
