#ifndef LINE_TREND_CONFIG_H
#define LINE_TREND_CONFIG_H

#define LINE_TREND_TIGHT_ERROR (3.0f)
#define LINE_TREND_OUTER_ERROR (4.0f)
#define LINE_TREND_HAIRPIN_ERROR (6.0f)
#define LINE_TREND_OUTWARD_STEPS (2U)
#define LINE_TREND_HAIRPIN_FRAMES (3U)
#define LINE_TREND_REACQUIRE_FRAMES (3U)
#define LINE_TREND_CORNER_WINDOW_MS (200U)
#define LINE_TREND_MIN_CONFIDENCE (40U)
#define LINE_TREND_CROSSLINE_ACTIVE_COUNT (4U)

#endif
