#ifndef LINE_EVENT_CONFIG_H
#define LINE_EVENT_CONFIG_H

#define LINE_EVENT_STABLE_SINGLE_FRAMES (3U)
#define LINE_EVENT_WIDE_CONFIRM_FRAMES (2U)
#define LINE_EVENT_WIDE_ACTIVE_COUNT (4U)
#define LINE_EVENT_WIDE_MIN_SPAN (4U)
#define LINE_EVENT_DIRECTION_THRESHOLD (4)
#define LINE_EVENT_SIDE_COUNT_WEIGHT (2)
#define LINE_EVENT_EDGE_WEIGHT (3)
#define LINE_EVENT_MIN_CONFIDENCE (40U)
#define LINE_EVENT_STALE_MS (20U)

#endif
