#ifndef ULTRASONIC_CONFIG_H
#define ULTRASONIC_CONFIG_H

#define ULTRASONIC_TRIGGER_PERIOD_US  (60000U)
#define ULTRASONIC_ECHO_TIMEOUT_US    (30000U)
#define ULTRASONIC_MIN_PULSE_US       (100U)
#define ULTRASONIC_MAX_PULSE_US       (25000U)

#endif
