#ifndef CORNER_MANEUVER_CONFIG_H
#define CORNER_MANEUVER_CONFIG_H

#define CORNER_PROBE_COMMAND (100)
#define CORNER_PROBE_MAX_MS (80U)
#define CORNER_BRAKE_MS (120U)
#define CORNER_COMMIT_MS (100U)
#define CORNER_SEEK_MAX_MS (900U)
#define CORNER_SETTLE_MS (300U)
#define CORNER_TOTAL_TIMEOUT_MS (2000U)
#define CORNER_INNER_COMMAND (-80)
#define CORNER_OUTER_COMMAND (120)
#define CORNER_REACQUIRE_FRAMES (3U)
#define CORNER_CENTER_ERROR (3.0f)
#define CORNER_MIN_CONFIDENCE (40U)
#define CORNER_FEATURE_STALE_MS (20U)

#endif
