#ifndef LINE_RECOVERY_CONFIG_H
#define LINE_RECOVERY_CONFIG_H

#define LINE_LOSS_CONFIRM_COUNT (3U)
#define LINE_REACQUIRE_COUNT (3U)
#define LINE_PIVOT_FORWARD_PERCENT (12)
#define LINE_SEARCH_INNER_PERCENT (8)
#define LINE_RECOVERY_MAX_YAW_DEG (45.0f)
#define LINE_RECOVERY_TIMEOUT_MS (3000U)
#define LINE_ALIGN_DURATION_MS (300U)
#define LINE_RECOVERY_ESTIMATE_STALE_MS (20U)

#define LINE_PIVOT_FORWARD_COMMAND (LINE_PIVOT_FORWARD_PERCENT * 10)
#define LINE_SEARCH_INNER_COMMAND (LINE_SEARCH_INNER_PERCENT * 10)

#endif
