#ifndef LINE_RECOVERY_CONFIG_H
#define LINE_RECOVERY_CONFIG_H

#define LINE_LOSS_CONFIRM_COUNT (3U)
#define LINE_REACQUIRE_COUNT (3U)
#define LINE_FORWARD_SEARCH_MS (500U)
#define LINE_REVERSAL_PAUSE_MS (120U)
#define LINE_BACKTRACK_MS (700U)
#define LINE_ALIGN_DURATION_MS (300U)
#define LINE_RECOVERY_TOTAL_TIMEOUT_MS (3000U)
#define LINE_RECOVERY_ESTIMATE_STALE_MS (20U)
#define LINE_RECOVERY_MIN_CONFIDENCE (40U)
#define LINE_RECOVERY_CENTER_ERROR (3.0f)

#define LINE_SEARCH_INNER_COMMAND (80)
#define LINE_SEARCH_OUTER_COMMAND (120)
#define LINE_CORNER_INNER_COMMAND (-80)
#define LINE_CORNER_OUTER_COMMAND (120)

#endif
