#ifndef LINE_RECOVERY_CONFIG_H
#define LINE_RECOVERY_CONFIG_H

#define LINE_LOSS_CONFIRM_COUNT (3U)
#define LINE_REACQUIRE_COUNT (3U)
#define LINE_PIVOT_FORWARD_PERCENT (27)
#define LINE_PIVOT_REVERSE_PERCENT (18)
#define LINE_RECOVERY_MAX_YAW_DEG (45.0f)
#define LINE_RECOVERY_TIMEOUT_MS (800U)
#define LINE_ALIGN_DURATION_MS (300U)
#define LINE_RECOVERY_ESTIMATE_STALE_MS (20U)

#define LINE_PIVOT_FORWARD_COMMAND (LINE_PIVOT_FORWARD_PERCENT * 10)
#define LINE_PIVOT_REVERSE_COMMAND (LINE_PIVOT_REVERSE_PERCENT * 10)

#endif
